image: archlinux
packages:
  - go
sources:
  - https://git.sr.ht/~humaid/shopsheet
tasks:
  - setup: |
      cd shopsheet
      go get ./...
  - format: |
      cd shopsheet
      go fmt $(go list ./... | grep -v /vendor/)
      go vet $(go list ./... | grep -v /vendor/)
  - test: |
      cd shopsheet
      go test -cover -race $(go list ./... | grep -v /vendor/)
  - build: |
      cd shopsheet
      go build

